export const copy = {
fr:{event:'UNE AVENTURE MUSICALE',day:'Jour',left:'Fin dans',progress:'Ton parcours musical',done:'Terminé',locked:'Bientôt',ready:'Disponible',hint:'Suis le rythme ! Ici, on ne perd jamais.',reward:'Gagne des points et reçois ton diplôme',result:'Bravo pour la musique !',saved:'Ton meilleur score est enregistré',continue:'Continuer',again:'Rejouer',ended:'Événement terminé !',thanks:'Merci pour ta musique',certificate:'Recevoir le diplôme',diploma:'DIPLÔME',for:'Pour ta participation à cette aventure musicale',gold:'Étoile du rythme',silver:'Maître des mélodies',bronze:'Ami de la musique',rotate:'Tourne ton appareil à la verticale',loading:'Accordage des instruments…',error:'Impossible de charger l’événement. Vérifie ta connexion.',retry:'Réessayer',paused:'Musique en pause',resume:'Continuer',start:'Commencer',tutorial:'Appuie sur le bouton quand la note le rejoint.',waiting:'L’événement commence bientôt',prototype:'Prototype · jour de l’événement',all:'Total de toutes les parties',close:'Fermer',audioError:'Impossible de charger la musique. Réessaie.'},
ru:{event:'МУЗЫКАЛЬНОЕ ПРИКЛЮЧЕНИЕ',day:'День',left:'До конца события',progress:'Твой музыкальный путь',done:'Пройдено',locked:'Скоро',ready:'Открыто',hint:'Лови ноты в ритм! Здесь нельзя проиграть.',reward:'Собери баллы и получи свою грамоту',result:'Отличная музыка!',saved:'Лучший результат сохранён',continue:'Продолжить',again:'Сыграть ещё',ended:'Ивент завершён!',thanks:'Спасибо за твою музыку',certificate:'Забрать грамоту',diploma:'ГРАМОТА',for:'За участие в музыкальном приключении',gold:'Звезда ритма',silver:'Мастер мелодии',bronze:'Друг музыки',rotate:'Поверни устройство вертикально',loading:'Настраиваем инструменты…',error:'Не удалось загрузить событие. Проверь подключение.',retry:'Повторить',paused:'Музыка на паузе',resume:'Продолжить',start:'Начать',tutorial:'Нажимай на кнопку, когда нота соединится с ней',waiting:'Событие скоро начнётся',prototype:'Прототип · день события',all:'Итого за все игры',close:'Закрыть',audioError:'Музыка не загрузилась. Попробуй ещё раз.'},
en:{event:'A MUSICAL ADVENTURE',day:'Day',left:'Event ends in',progress:'Your musical journey',done:'Completed',locked:'Soon',ready:'Available',hint:'Catch the rhythm! There is no losing here.',reward:'Collect points and earn your certificate',result:'Beautiful music!',saved:'Your best score is saved',continue:'Continue',again:'Play again',ended:'Event complete!',thanks:'Thank you for your music',certificate:'Get certificate',diploma:'CERTIFICATE',for:'For taking part in the musical adventure',gold:'Rhythm star',silver:'Melody master',bronze:'Music friend',rotate:'Turn your device to portrait',loading:'Tuning the instruments…',error:'Could not load the event. Check your connection.',retry:'Retry',paused:'Music paused',resume:'Resume',start:'Start',tutorial:'Tap the button when the note meets it.',waiting:'The event starts soon',prototype:'Prototype · event day',all:'Total across all games',close:'Close',audioError:'Music could not load. Please try again.'},
ar:{event:'مغامرة موسيقية',day:'اليوم',left:'ينتهي الحدث خلال',progress:'رحلتك الموسيقية',done:'مكتمل',locked:'قريبًا',ready:'متاح',hint:'اتبع الإيقاع! لا توجد خسارة هنا.',reward:'اجمع النقاط واحصل على شهادتك',result:'موسيقى رائعة!',saved:'تم حفظ أفضل نتيجة',continue:'متابعة',again:'العب مجددًا',ended:'اكتمل الحدث!',thanks:'شكرًا على موسيقاك',certificate:'احصل على الشهادة',diploma:'شهادة',for:'للمشاركة في المغامرة الموسيقية',gold:'نجم الإيقاع',silver:'ماهر الألحان',bronze:'صديق الموسيقى',rotate:'أدر جهازك عموديًا',loading:'جارٍ تجهيز الآلات…',error:'تعذر تحميل الحدث. تحقق من الاتصال.',retry:'حاول مجددًا',paused:'الموسيقى متوقفة مؤقتًا',resume:'متابعة',start:'ابدأ',tutorial:'اضغط على الزر عندما تصل النوتة إليه.',waiting:'سيبدأ الحدث قريبًا',prototype:'نموذج أولي · يوم الحدث',all:'مجموع كل الألعاب',close:'إغلاق',audioError:'تعذر تحميل الموسيقى. حاول مجددًا.'},
hi:{event:'एक संगीत रोमांच',day:'दिन',left:'इवेंट समाप्त होने में',progress:'आपकी संगीत यात्रा',done:'पूरा',locked:'जल्द',ready:'उपलब्ध',hint:'लय पकड़ो! यहाँ कोई हार नहीं है।',reward:'अंक जुटाओ और प्रमाणपत्र पाओ',result:'सुंदर संगीत!',saved:'आपका सर्वश्रेष्ठ स्कोर सहेजा गया',continue:'जारी रखें',again:'फिर खेलें',ended:'इवेंट पूरा हुआ!',thanks:'आपके संगीत के लिए धन्यवाद',certificate:'प्रमाणपत्र लें',diploma:'प्रमाणपत्र',for:'संगीत रोमांच में भाग लेने के लिए',gold:'लय का सितारा',silver:'धुन के उस्ताद',bronze:'संगीत मित्र',rotate:'डिवाइस को सीधा घुमाएँ',loading:'वाद्य तैयार हो रहे हैं…',error:'इवेंट लोड नहीं हुआ। कनेक्शन जाँचें।',retry:'फिर कोशिश करें',paused:'संगीत रुका है',resume:'जारी रखें',start:'शुरू करें',tutorial:'जब नोट बटन से मिले, तब बटन दबाओ।',waiting:'इवेंट जल्द शुरू होगा',prototype:'प्रोटोटाइप · इवेंट का दिन',all:'सभी खेलों का कुल स्कोर',close:'बंद करें',audioError:'संगीत लोड नहीं हुआ। फिर कोशिश करें।'}
};
const visualCopy={
 fr:{demoPlayer:'Joueur',you:'Toi',demoRanking:'Classement de démonstration',getDiploma:'Recevoir le diplôme',preview:'Aperçus',menuPreview:'Menu',resultPreview:'Résultat',winPreview:'Final'},
 ru:{demoPlayer:'Игрок',you:'Ты',demoRanking:'Демо-таблица · не серверный рейтинг',getDiploma:'Забрать диплом',preview:'Макеты',menuPreview:'Меню',resultPreview:'Результат',winPreview:'Финал'},
 en:{demoPlayer:'Player',you:'You',demoRanking:'Demo table · not a live ranking',getDiploma:'Get diploma',preview:'Layouts',menuPreview:'Menu',resultPreview:'Result',winPreview:'Final'},
 ar:{demoPlayer:'لاعب',you:'أنت',demoRanking:'جدول تجريبي · ليس ترتيبًا مباشرًا',getDiploma:'احصل على الشهادة',preview:'التصاميم',menuPreview:'القائمة',resultPreview:'النتيجة',winPreview:'النهاية'},
 hi:{demoPlayer:'खिलाड़ी',you:'आप',demoRanking:'डेमो तालिका · लाइव रैंकिंग नहीं',getDiploma:'प्रमाणपत्र लें',preview:'लेआउट',menuPreview:'मेनू',resultPreview:'परिणाम',winPreview:'अंत'}
};
for(const language of Object.keys(copy))Object.assign(copy[language],visualCopy[language]);

const integrationCopy={
 ru:{local:'Результат сохранён на устройстве',syncing:'Сохраняем результат…',synced:'Результаты синхронизированы',syncFailed:'Не удалось обновить данные. Повтори синхронизацию.',serverRanking:'Рейтинг игроков',connectionError:'Не удалось подключить событие. Проверь подключение и открой игру из приложения заново.'},
 en:{local:'Saved on this device',syncing:'Saving your result…',synced:'Results synchronized',syncFailed:'Could not update results. Retry synchronization.',serverRanking:'Player leaderboard',connectionError:'Could not connect to the event. Check your connection and reopen the game from the app.'},
 fr:{local:'Enregistré sur cet appareil',syncing:'Enregistrement du résultat…',synced:'Résultats synchronisés',syncFailed:'Impossible de mettre à jour les résultats. Réessaie.',serverRanking:'Classement des joueurs',connectionError:'Connexion à l’événement impossible. Vérifie ta connexion et rouvre le jeu depuis l’application.'},
 ar:{local:'محفوظ على الجهاز',syncing:'جارٍ حفظ النتيجة…',synced:'تمت مزامنة النتائج',syncFailed:'تعذر تحديث النتائج. حاول المزامنة مجددًا.',serverRanking:'ترتيب اللاعبين',connectionError:'تعذر الاتصال بالحدث. تحقق من الاتصال وأعد فتح اللعبة من التطبيق.'},
 hi:{local:'इस डिवाइस पर सहेजा गया',syncing:'परिणाम सहेज रहे हैं…',synced:'परिणाम सिंक हो गए',syncFailed:'परिणाम अपडेट नहीं हुए। फिर सिंक करें।',serverRanking:'खिलाड़ियों की रैंकिंग',connectionError:'इवेंट से जुड़ नहीं पाए। कनेक्शन जाँचें और ऐप से गेम फिर खोलें।'},
};
for(const language of Object.keys(copy))Object.assign(copy[language],integrationCopy[language]);
